/**
 * Streaming TTS Endpoint - Real-time audio delivery
 *
 * Instead of buffering the entire audio, this streams chunks directly
 * to the client as they're generated by OpenAI, reducing perceived latency
 * from ~27s to ~2-3s for first audio playback.
 */

import { NextRequest, NextResponse } from 'next/server';
import OpenAI from 'openai';
import { OPENAI_CONFIG, TTS_CONFIG } from '@/config/constants';

export async function POST(request: NextRequest) {
  const startTime = performance.now();

  try {
    const { text } = await request.json();

    if (!text) {
      return NextResponse.json({ error: 'Text required' }, { status: 400 });
    }

    if (!OPENAI_CONFIG.apiKey) {
      return NextResponse.json({ error: 'OpenAI API key not configured' }, { status: 500 });
    }

    const client = new OpenAI({
      apiKey: OPENAI_CONFIG.apiKey,
      timeout: TTS_CONFIG.timeoutMs,
    });

    // Request streaming response from OpenAI
    const response = await client.audio.speech.create({
      model: OPENAI_CONFIG.ttsModel,
      voice: OPENAI_CONFIG.ttsVoice as any,
      input: text,
      response_format: 'mp3',
    });

    // Get the response body as a readable stream
    const audioStream = response.body;

    if (!audioStream) {
      return NextResponse.json({ error: 'No audio stream received' }, { status: 500 });
    }

    const duration = ((performance.now() - startTime) / 1000).toFixed(3);
    console.log(`[TIMING] TTS Stream started (OpenAI ${OPENAI_CONFIG.ttsVoice}): ${duration}s to first byte`);

    // Stream the audio directly to the client
    return new NextResponse(audioStream as ReadableStream, {
      headers: {
        'Content-Type': 'audio/mpeg',
        'Transfer-Encoding': 'chunked',
        'Cache-Control': 'no-cache',
      },
    });
  } catch (error: any) {
    console.error('[TTS Stream] Error:', error.message);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
